cleaning = {
  'V200004':'1.pre-election interview (only) complete 2.post-election interview (only) complete 3.pre and post-election interviews (both) complete',
  'V200002': '1.Video 2.Telephone 3.Web'
}

demographics = {
  'V201200': ('Where would you place yourself on this scale, or havent you thought much about this?','-9.Refused 1.Extremely liberal 2.Liberal 3.Slightly liberal 4.Moderate; middle of the road 5.Slightly conservative 6.Conservative 7.Extremely conservative 99.Havent thought much about this'),
  'V201600': ('What is your sex?','-9.Refused 1.Male 2.Female'),
}

battery = {
"V201119": ("How happy do you feel about how things are going in the country?", "-9.Refused 1.Not at all 2.A little 3.Somewhat 4.Very 5.Extremely"),
'V201156': ('Id like to get your feelings toward some of our political leaders and other people who are in the news these days. Ill read the name of a person and Id like you to rate that person using something we call the feeling thermometer. Ratings between 50 degrees and 100 degrees mean that you feel favorable and warm toward the person. Ratings between 0 degrees and 50 degrees mean that you dont feel favorable toward the person and that you dont care too much for that person. You would rate the person at the 50 degree mark if you dont feel particularly warm or cold toward the person. If we come to a person whose name you dont recognize, you dont need to rate that person. Just tell me and well move on to the next one. How would you rate: the Democratic Party','-9.Refused 998.Dont know (dont know where to rate)'),
'V201157': ('Id like to get your feelings toward some of our political leaders and other people who are in the news these days. Ill read the name of a person and Id like you to rate that person using something we call the feeling thermometer. Ratings between 50 degrees and 100 degrees mean that you feel favorable and warm toward the person. Ratings between 0 degrees and 50 degrees mean that you dont feel favorable toward the person and that you dont care too much for that person. You would rate the person at the 50 degree mark if you dont feel particularly warm or cold toward the person. If we come to a person whose name you dont recognize, you dont need to rate that person. Just tell me and well move on to the next one. How would you rate: the Republican Party','-9.Refused 998.Dont know (dont know where to rate)'),
'V201208': ('Think about Joe Biden. In your opinion, does the phrase \'he provides strong leadership\' describe Joe Biden extremely well, very well, moderately well, slightly well, or not well at all?','-9. Refused 1.Extremely well 2.Very well 3.Moderately well 4.Slightly well 5.Not well at all'),
'V201212': ('Think about Donald Trump. In your opinion, does the phrase \'he provides strong leadership\' describe Donald Trump extremely well, very well, moderately well, slightly well, or not well at all?','-9. Refused 1.Extremely well 2.Very well 3.Moderately well 4.Slightly well 5.Not well at all'),
'V201233': ('How often can you trust the federal government in Washington to do what is right?','-9.Refused 1.Always 2.Most of the time 3.About half the time 4.Some of the time 5.Never'),
'V201246': ('Some people think the government should provide fewer services even in areas such as health and education in order to reduce spending. Suppose these people are at one end of a scale, at point 1. Other people feel it is important for the government to provide many more services even if it means an increase in spending. Suppose these people are at the other end, at point 7. And, of course, some other people have opinions somewhere in between, at points 2, 3, 4, 5 or 6. Where would you place yourself on this scale, or havent you thought much about this?','-9. Refused 1.Government should provide many fewer services 2. 3. 4. 5. 6. 7.Government should provide many more services 99.Havent thought much about this'),
'V201249': ('Some people believe that we should spend much less money for defense. Suppose these people are at one end of a scale, at point 1. Others feel that defense spending should be greatly increased. Suppose these people are at the other end, at point 7. And, of course, some other people have opinions somewhere in between, at points 2, 3, 4, 5 or 6. Where would you place yourself on this scale, or havent you thought much about this?','-9.Refused 1.Greatly decrease defense spending 2. 3. 4. 5. 6. 7.Greatly increase defense spending 99. Havent thought much about this'),
'V201252': ('There is much concern about the rapid rise in medical and hospital costs. Some people feel there should be a government insurance plan which would cover all medical and hospital expenses for everyone. Suppose these people are at one end of a scale, at point 1. Others feel that all medical expenses should be paid by individuals through private insurance plans like Blue Cross or other company paid plans. Suppose these people are at the other end, at point 7. And, of course, some other people have opinions somewhere in between, at points 2, 3, 4, 5, or 6. Where would you place yourself on this scale, or havent you thought much about this?','-9.Refused 1.Government insurance plan 2. 3. 4. 5. 6. 7.Private insurance plan 99.Havent thought much about this'),
'V201255': ('Some people feel the government in Washington should see to it that every person has a job and a good standard of living. Suppose these people are at one end of a scale, at point 1. Others think the government should just let each person get ahead on their own. Suppose these people are at the other end, at point 7. And, of course, some other people have opinions somewhere in between, at points 2, 3, 4, 5, or 6. Where would you place yourself on this scale, or havent you thought much about this?','-9.Refused 1.Government should see to jobs and standard of living 2. 3. 4. 5. 6. 7.Government should let each person get ahead on own 99. Havent thought much about this'),
'V201258': ('Some people feel that the government in Washington should make every effort to improve the social and economic position of blacks. Suppose these people are at one end of a scale, at point 1. Others feel that the government should not make any special effort to help blacks because they should help themselves. Suppose these people are at the other end, at point 7. And, of course, some other people have opinions somewhere in between, at points 2, 3, 4, 5, or 6. Where would you place yourself on this scale, or havent you thought much about this?','-9. Refused 1.Government should help blacks 2. 3. 4. 5. 6. 7.Blacks should help themselves 99. Havent thought much about this'),
'V201262': ('Some people think we need much tougher government regulations on business in order to protect the environment. Suppose these people are at one end of a scale, at point 1. Others think that current regulations to protect the environment are already too much of a burden on business. Suppose these people are at the other end, at point 7. And, of course, some other people have opinions somewhere in between, at points 2,3,4,5, or 6. Where would you place yourself on this scale, or havent you thought much about this?','-9.Refused 1.Tougher regulations on business needed to protect environment 2. 3. 4. 5. 6. 7.Regulations to protect environment already too much a burden on business 99.Havent thought much about this'),
'V201350': ('How willing should the United States be to use military force to solve international problems?','-9.Refused 1.Extremely willing 2.Very willing 3.Moderately willing 4.A little willing 5.Not at all willing'),
'V201365': ('If the COVID-19 pandemic continues through Election Day in November, what do you think should be done?','-9.Refused 1.Delay the election 2.Have all voters mail in their ballots 3.Proceed with in-person voting, but require social distancing at voting locations 4.Proceed as normal with no extra precautions'),
'V201366': ('How important is it that news organizations are free to criticize political leaders?','-9.Refused 1.Not important at all 2.A little important 3.Moderately important 4.Very important 5.Extremely important'),
'V201368': ('How important is it that elected officials face serious consequences if they engage in misconduct?','-9.Refused 1.Not important at all 2.A little important 3.Moderately important 4.Very important 5.Extremely important'),
'V201377': ('In general, how much trust and confidence do you have in the news media when it comes to reporting the news fully, accurately, and fairly?','-9.Refused 1.None 2.A little 3.A moderate amount 4.A lot 5.A great deal'),
"V201626": ("Some people think that the way people talk needs to change with the times to be more sensitive to people from different backgrounds. Others think that this has already gone too far and many people are just too easily offended. Which is closer to your opinion?", "-9. Refused 1.The way people talk needs to change a lot 2.The way people talk needs to change a little 3.People are a little too easily offended 4.People are much too easily offended"),
"V201651": ("All things considered, how satisfied are you with your life as a whole these days?Would you say that you are extremely satisfied, very satisfied, moderately satisfied, slightly satisfied, or not satisfied at all?", "-9.Refused 1.Extremely satisfied 2.Very satisfied 3.Moderately satisfied 4.Slightly satisfied 5.Not satisfied at all"),
}